### ISSUE TITLE
分页组件hidden参数不起作用

### ISSUE THREAD

**Issue by dai-yi-heng** [youlaitech/vue3-element-admin#10]
![image](https://github.com/youlaitech/vue3-element-admin/assets/92423893/eef453f3-ef56-4b6f-9d38-a67c6408379a)
![image](https://github.com/youlaitech/vue3-element-admin/assets/92423893/c812d42c-2c37-44e6-bf64-35c8f3c5a0d8)

**Comment by AprilTong** [comment]
感谢告知，已修复。
