### ISSUE TITLE
签名保存至后端无反应

### ISSUE THREAD

**Issue by dai-yi-heng** [youlaitech/vue3-element-admin#11]
![image](https://github.com/youlaitech/vue3-element-admin/assets/92423893/d2265a7d-3f45-46df-b32a-8a3e2f0ad317)
z'c正常操作下走不进去这个if判断；取消 !mime.length 这个条件保存文件的接口也会报签名不一致的错误
![image](https://github.com/youlaitech/vue3-element-admin/assets/92423893/94e467e9-c606-43f3-8598-ce10ea623550)

**Comment by AprilTong** [comment]
判断、取值有点问题，已修复。
![image](https://github.com/youlaitech/vue3-element-admin/assets/24354441/3048df7c-7a8d-4e2f-92ae-c0e5e1150254)
