### ISSUE TITLE
菜单栏选择顶部怎么不生效

### ISSUE THREAD

**Issue by wangling404** [youlaitech/vue3-element-admin#13]

**Comment by COOlJJJ** [comment]
同问

**Comment by haoxianrui** [comment]
@COOlJJJ  但凡看下代码就不会这么问，导航栏没绑定事件，目前就是个初期样式，后面空了会加上空了会加上

**Comment by COOlJJJ** [comment]
谢谢回复

**Comment by haoxianrui** [comment]
@COOlJJJ 您客气了

**Comment by haoxianrui** [comment]
https://github.com/youlaitech/vue3-element-admin/commit/cc721dfba11eb53d8dc6a082016ef4832d21a516
