### ISSUE TITLE
curd 页面中搜索框怎么没显示出来呢？

### ISSUE THREAD

**Issue by jocongmin** [youlaitech/vue3-element-admin#130]
![image](https://github.com/youlaitech/vue3-element-admin/assets/12780726/55a964b1-2049-4d0c-a154-015c4fd6b858)

**Comment by haoxianrui** [comment]
可以了重新看下，线上权限缓存被覆盖了
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/af8b725b-4f91-4463-8922-9b8b8307dc07)

**Comment by jocongmin** [comment]
您的邮件我已收到，谢谢。
