### ISSUE TITLE
为啥我的按需引入ElMessage, ElMessageBox...这些都没引进来

### ISSUE THREAD

**Issue by kuangqie** [youlaitech/vue3-element-admin#14]
import { ElementPlusResolver } from 'unplugin-vue-components/resolvers'
import Icons from 'unplugin-icons/vite'
import IconsResolver from 'unplugin-icons/resolver'
resolvers: [
  // 自动导入 Element Plus 相关函数，如：ElMessage, ElMessageBox... (带样式)
  ElementPlusResolver(),
  IconsResolver({}),
],
我都复制粘贴了也没用

**Comment by AprilTong** [comment]
添加更改相关配置后，要打开自动生成，重新生成auto-imports文件。这样auto-imports中会有ElMessageBox等函数。
<img width="1130" alt="image" src="https://github.com/youlaitech/vue3-element-admin/assets/24354441/3c90aea8-122a-4c57-b119-bdcf9c6f749b">

**Comment by kuangqie** [comment]
我的是一直打开的，每次我会将auto-important内容清空重新生成，但是一直没有，是不是还有其他地方配置呢，我看文档上面没有特殊的点
这是我在csdn上面看到的
<img width="798" alt="image" src="https://github.com/youlaitech/vue3-element-admin/assets/46955073/5ce9822b-618c-48b0-b7c7-34c9dcfd4d9a">
想看看这一步您这边怎么处理的

**Comment by haoxianrui** [comment]
@kuangqie 文档已经都说了，主要安装依赖 npm install -D unplugin-auto-import unplugin-vue-components 剩下就是vite.config.ts 里的配置，你好好对比下当前项目，不行去官方库的issue看看
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/fc663f2e-ff82-4b85-8519-09b3fce87951)
