### ISSUE TITLE
关于增加用户列表属性修改权限点的申请

### ISSUE THREAD

**Issue by cshaptx4869** [youlaitech/vue3-element-admin#144]
属性修改：指的是列表单字段的修改。比如，用户列表的status字段，如果做成switch效果，那么就可以修改状态，提交给接口数据格式为 `{id:xxx, field: 'status', value: xxx}`
CURD组件中默认支持属性修改，但是现在没有属性修改的权限点，所以默认是不允许修改（disabled），如果要体验的话要麻烦大大增加一个属性修改的权限点标识，比如 `sys:user:modify`

![Snipaste_2024-06-17_14-00-27](https://github.com/youlaitech/vue3-element-admin/assets/31907940/ea841d92-cb92-4709-852a-946da3ffc053)

**Comment by haoxianrui** [comment]
@cshaptx4869  才看到，已加。后面有空我整个权限标识的约定说明
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/00c9c51e-9159-4375-b734-54eebc32b47f)
