### ISSUE TITLE
v2.11.2，页面菜单路由跳转卡死

### ISSUE THREAD

**Issue by Gentlest** [youlaitech/vue3-element-admin#145]
![image](https://github.com/youlaitech/vue3-element-admin/assets/56472665/be6d3220-7ba9-4a77-912e-b6f0642c2f8b)
目前页面刷新进入任意一个菜单，然后再次点击其他菜单，路由就无法正常跳转

**Comment by haoxianrui** [comment]
@Gentlest  尝试禁用 VueDevTools 插件
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/4179a8bc-242d-4d81-80eb-280b04626019)

**Comment by Gentlest** [comment]
> @Gentlest 尝试禁用 VueDevTools 插件 ![image](https://private-user-images.githubusercontent.com/12759477/340483628-4179a8bc-242d-4d81-80eb-280b04626019.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2NzM1NjQsIm5iZiI6MTcxODY3MzI2NCwicGF0aCI6Ii8xMjc1OTQ3Ny8zNDA0ODM2MjgtNDE3OWE4YmMtMjQyZC00ZDgxLTgwZWItMjgwYjA0NjI2MDE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAxMTQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1MzY4MWIyNjE3OTlkZWM5Mjg1YjRhYmYxODgzYWNiZDhiYjAwNmI3OGEzOTkxNWM3ZTcwN2ZmMWNkOTllZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e5v4reREXwh5p4pWZlPQwTriqu4FgBsFtQms52P00Tg)

感谢，已解决
