### ISSUE TITLE
项目初始话失败，提示Vue packages version mismatch:

### ISSUE THREAD

**Issue by liuyunchuan** [youlaitech/vue3-element-admin#147]
我电脑是mac系统，npm是10.2.4， node 是18.19.1，报错之后，试过卸载vue-template-compiler（pnpm uninstall vue-template-compiler），并且安装sfc（pnpm install @vue/compiler-sfc@3.4.29），还是有这个报错，我应该如何解决。
![2222222](https://github.com/youlaitech/vue3-element-admin/assets/26404926/0dbdb669-2961-4c73-8914-3264d60c03ad)

**Comment by haoxianrui** [comment]
目前 github 和这个相关的 issue 基本是 open 状态。
我看群里有人解决是 pnpm 残留了 vue 2.7 ，所以尝试清理 pnpm 的缓存或者卸载 pnpm 看看。
当前只是建议，目前我这边没有机器能够复现这个问题。有进展还希望告知下，感谢！

**Comment by liuyunchuan** [comment]
我通过全局搜索vue-template-compiler，发现只有在node_moules里面存在vue-template-compiler，并且存在2.6.12的版本和2.7.16版本。
![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/ed0fc0c6-5e09-4a9f-9fd0-0a31c446dcac)
删除node_moules 和 package-lock.json 后，全局搜索不到 vue-template-compiler 相关内容
![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/2ec4c769-3353-4871-9e72-ae0a501312ee)

运行pnpm install安装正常
![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/3e005671-3e74-4c59-bf36-4327232ed525)

运行pnpm list vue，只看的vue 3.4.29版本，没看到vue2
![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/d88089de-b105-4cee-a19f-97a2aa617861)
再次全局搜索vue-template-compiler，又出现了
![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/39db178b-e99c-49fa-b3e8-fda3a21cc192)
看看我提供的这些信息能不能大概定位出问题，感谢！！！

**Comment by haoxianrui** [comment]
@liuyunchuan  
升级 unplugin-icons 版本到 v0.19.0试试 
https://github.com/unplugin/unplugin-icons/releases/tag/v0.19.0
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/018192c3-62b0-40bb-8fb3-d24d4bc1b77f)

**Comment by liuyunchuan** [comment]
升级 unplugin-icons 版本到 v0.19.0了，问题还是存在
![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/fb288746-17a0-4aa9-bde2-a5b8ec13875a)

![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/5b115d4d-a9e3-4602-b307-82938833a7c7)

![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/081e1354-926c-4da3-a986-dc8df309ce33)

![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/2a9c5b6b-e5dc-47f1-ac92-5603f7ef9b7a)

**Comment by liuyunchuan** [comment]
好像是因为unplugin-icons 0.19.0 和 vue-tsc 2.0.21都有依赖 vue-template-compiler

![image](https://github.com/youlaitech/vue3-element-admin/assets/26404926/61d4d4d9-1b1b-48fc-b2e9-74bd5a8d7da6)

**Comment by haoxianrui** [comment]
@liuyunchuan  很奇怪 , 我的机器无论 unplugin-icons 0.19.0  还是 旧版的 0.18.5 ，解析   vue-template-compiler  依赖时都没显示，所以问题应该还是出现在 unplugin-icons 组件上
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/db0d4454-12f4-4714-bf13-5413dae2b481)
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/1683d32b-ecb8-42f6-8d15-ccd8d42af1a9)

**Comment by haoxianrui** [comment]
@liuyunchuan 试着移除 unplugin-icons 组件看下情况
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/5d9e75ed-6a7b-4ddd-9416-6304de21e9d9)

**Comment by liuyunchuan** [comment]
找了一个windows的电脑，cmd那边没有报错信息，当时登录之后页面没有内容

![Uploading image.png…]()

![Uploading image.png…]()

**Comment by haoxianrui** [comment]
@liuyunchuan  这又是另一个错误了，也是比较少见，都被你碰到了。wins 这台机器你试着打开自动导入组件重新生成
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/673bb352-e3df-4e96-bb39-41241468becf)
