### ISSUE TITLE
启用Mock服务报错

### ISSUE THREAD

**Issue by cshaptx4869** [youlaitech/vue3-element-admin#159]
最新的代码开启 Mock 服务会报错

![PixPin_2024-08-12_11-31-53](https://github.com/user-attachments/assets/52a7befb-e433-4ba3-a486-a9d990bc0001)

**Comment by haoxianrui** [comment]
@cshaptx4869  node 版本多少？ 我这 v20.6.1 测试没有出现图中的报错。
![image](https://github.com/user-attachments/assets/0d494c18-372c-4a0d-9016-66423062e6b8)

**Comment by cshaptx4869** [comment]
Node 版本 20.11.1，就很奇怪mock服务突然就不行了。。。报这个错误

**Comment by haoxianrui** [comment]
@cshaptx4869  我看你得项目在c盘，你换个盘试下，很多奇怪问题是把项目放到c盘导致的

**Comment by cshaptx4869** [comment]
放e盘也是提示同样的错误，感觉像是vite-plugin-mock-dev-server库在找mock文件时提示的路径错误，我把*.mock.ts文件改名为*.mock.ts.bak后就不会有这个报错

**Comment by cshaptx4869** [comment]
> @cshaptx4869 node 版本多少？ 我这 v20.6.1 测试没有出现图中的报错。 ![image](https://private-user-images.githubusercontent.com/12759477/356936743-0d494c18-372c-4a0d-9016-66423062e6b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NTM2MDYsIm5iZiI6MTcyMzQ1MzMwNiwicGF0aCI6Ii8xMjc1OTQ3Ny8zNTY5MzY3NDMtMGQ0OTRjMTgtMzcyYy00YTBkLTkwMTYtNjY0MjMwNjJlNmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA5MDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2ZTY0MzE2NzFjZDVkMjc5NzgzMTJkNzVlNjlhNTM5YmMwMzZlMjViNWViN2VmOGU4ZjI4N2RjZGYyZWY5NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bfZ7tIcslgku7Pj5Y5h-o6xYxl0-xrqhlmb9aDMsi3M)

看 vite 版本好像不是最新的，最新的代码安装后， vite 是 5.4.0

**Comment by haoxianrui** [comment]
@cshaptx4869  现在仓库vite依赖是5.3.5。执行完pnpm update 更新到 5.4.0 版本报一样的错了

**Comment by cshaptx4869** [comment]
@haoxianrui 有没找到解决方法

**Comment by haoxianrui** [comment]
@cshaptx4869 没呢，先不升级vite版本再等一段时间看下

**Comment by haoxianrui** [comment]
@cshaptx4869 vite-plugin-mock-dev-server 官方已修复  https://github.com/pengzhanbo/vite-plugin-mock-dev-server/releases/tag/v1.7.1
