### ISSUE TITLE
template里使用$router toRow类似的类型报错

### ISSUE THREAD

**Issue by XHNLYW** [youlaitech/vue3-element-admin#163]
![20240829171118](https://github.com/user-attachments/assets/199aae61-109e-4087-bc9f-2a0fde8169a1)

**Comment by AnAloneJaver** [comment]
![image](https://github.com/user-attachments/assets/ebe3d9c1-e873-4c6c-8f0f-a50d97644d23)
没看懂你这个想表达什么意思，这里click想跳转路由的写法应该是这样
