### ISSUE TITLE
求大佬帮帮忙。项目的部署看不懂，演示环境禁止新增、修改和删除数据，请本地部署后测试”，该怎么消除。

### ISSUE THREAD

**Issue by jiangchengjie** [youlaitech/vue3-element-admin#23]
上传文件至远程服务器
将打包生成在 dist 目录下的文件拷贝至 /usr/share/nginx/html 目录

nginx.cofig 配置
server {
listen 80;
server_name localhost;
location / {
root /usr/share/nginx/html;
index index.html index.htm;
}
# 反向代理配置
location /prod-api/ {
proxy_pass [http://vapi.youlai.tech/](https://gitee.com/link?target=http%3A%2F%2Fvapi.youlai.tech%2F); # vapi.youlai.tech替换成你的后端API地址
}
}

这几个步骤一直没有头绪，还有“演示环境禁止新增、修改和删除数据，请本地部署后测试”，该怎么消除

**Comment by haoxianrui** [comment]
首先这个Nginx部署是很基础的东西。
另外“演示环境禁止新增、修改和删除数据，请本地部署后测试”是你调用的接口是默认有来线上的接口，需要你部署后端工程并修改数据库地址为你的本地环境。
