### ISSUE TITLE
在路由中使用外部连接进行跳转，是否有使用案例呢

### ISSUE THREAD

**Issue by songmengda** [youlaitech/vue3-element-admin#25]
https://github.com/youlaitech/vue3-element-admin/blob/533f389cf6bf94150c39f0c486b343b69174e706/src/router/index.ts#L57C1-L67C8

这样写能正常进行跳转吗，在views中并没有找到external-link相关的内容

**Comment by haoxianrui** [comment]
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/4a9a9209-56a9-4a01-bccc-5ac3496342f3)
![Uploading image.png…]()
