### ISSUE TITLE
.prettier 没到字数等号后自动换行问题

### ISSUE THREAD

**Issue by cshaptx4869** [youlaitech/vue3-element-admin#26]
.prettierrc.cjs 中的 printWidth 配置为 100 ，且项目重新跑过，保存代码时还是在等号那边换行，本身字数没到 100，这是什么问题

**Comment by haoxianrui** [comment]
![image](https://github.com/youlaitech/vue3-element-admin/assets/12759477/c59dcb15-51d6-4bad-84fe-1a1e6164b777)

**Comment by haoxianrui** [comment]
// 超出打印宽度 (always | never | preserve )
  proseWrap: "always",

**Comment by cshaptx4869** [comment]
> ![image](https://private-user-images.githubusercontent.com/12759477/308080375-c59dcb15-51d6-4bad-84fe-1a1e6164b777.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMjA1OTQsIm5iZiI6MTcwOTAyMDI5NCwicGF0aCI6Ii8xMjc1OTQ3Ny8zMDgwODAzNzUtYzU5ZGNiMTUtNTFkNi00YmFkLTg0ZmUtMWExZTYxNjRiNzc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA3NTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZTQ5ODE4MDhhYzI4MDc1NzAxNzhkZmU5OGZmYmFlY2EzN2ZkNDdmZGUzMTA3NzlmYjZkMmRhNzA3ZWEwMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9_xxYeEGxjVafMJhDFUNGODOMs2sbNUWql7f6fvAAGU)

很棒 解决了 感谢 Thanks♪(･ω･)ﾉ
