### ISSUE TITLE
大佬，想请教下为啥store里的写法不太一样

### ISSUE THREAD

**Issue by warjudge** [youlaitech/vue3-element-admin#32]
下面这两个defineStore，为啥第一个要包一层后才导出
<img width="944" alt="1709106934968" src="https://github.com/youlaitech/vue3-element-admin/assets/37129240/839836ea-ebc9-4a26-b175-cee6f82f2fa2">
<img width="825" alt="1709106964916" src="https://github.com/youlaitech/vue3-element-admin/assets/37129240/8da59371-a59b-4feb-9211-ee9f19f5d32d">

**Comment by cshaptx4869** [comment]
Pinia 官方文档：[在组件外使用 store](https://pinia.vuejs.org/zh/core-concepts/outside-component-usage.html#using-a-store-outside-of-a-component)
Pinia store 依靠 pinia 实例在所有调用中共享同一个 store 实例。大多数时候，只需调用你定义的 useStore() 函数，完全开箱即用。例如，在 setup() 中，你不需要再做任何事情。但在组件之外，情况就有点不同了。 实际上，useStore() 给你的 app 自动注入了 pinia 实例。这意味着，如果 pinia 实例不能自动注入，你必须手动提供给 useStore() 函数。 你可以根据不同的应用，以不同的方式解决这个问题。

**Comment by warjudge** [comment]
好的，万分感谢，官网中的意思是要把usePermissionStore写在路由守卫里面，这样就不用在外面包一层了，是吧
<img width="806" alt="1709111154268" src="https://github.com/youlaitech/vue3-element-admin/assets/37129240/20d7a9a5-4732-4fd4-b198-5657d206099e">
但是我试了下还是会报错。。。
不过我另外一个项目中就不会报错，如下
<img width="827" alt="1709111343886" src="https://github.com/youlaitech/vue3-element-admin/assets/37129240/966ef81c-1c1f-4669-a8fc-2e3e31181aed">

**Comment by warjudge** [comment]
哎，算了，不纠结了，谢谢大佬！！！

**Comment by cshaptx4869** [comment]
简单来说，报错是因为使用pinia在app.use()注册之前，如果要在pinia注册之前使用store的话，必须手动传入pinia实例

**Comment by warjudge** [comment]
嗯嗯，了解！
