### ISSUE TITLE
在request.ts文件中使用store中language值报错Uncaught ReferenceError: Cannot access 'store' before initialization

### ISSUE THREAD

**Issue by AH1013756399** [youlaitech/vue3-element-admin#67]
![1712887458444](https://github.com/youlaitech/vue3-element-admin/assets/63224656/2175e897-34f8-44aa-84dc-a3f5396e9e94)
![1712887558342](https://github.com/youlaitech/vue3-element-admin/assets/63224656/e214e199-91a4-4c79-914a-2cbc95c1ed03)

**Comment by AprilTong** [comment]
> ![1712887458444](https://private-user-images.githubusercontent.com/63224656/321832792-2175e897-34f8-44aa-84dc-a3f5396e9e94.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTgxNDgsIm5iZiI6MTcxODk1Nzg0OCwicGF0aCI6Ii82MzIyNDY1Ni8zMjE4MzI3OTItMjE3NWU4OTctMzRmOC00NGFhLTg0ZGMtYTNmNTM5NmU5ZTk0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA4MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4ZGFiMmM0NjVmYTBmY2UwNzgxYmU2ZWY5M2E5NTZmNDA1Yzg5MGUyMzUwYTZjMjM1MzY5ZDY2ODg2YjdjZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NEgQNMr_N91_uZt8_GJ8Oe8kPa098kKz8VMq_xFqzpI) ![1712887558342](https://private-user-images.githubusercontent.com/63224656/321832775-e214e199-91a4-4c79-914a-2cbc95c1ed03.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NTgxNDgsIm5iZiI6MTcxODk1Nzg0OCwicGF0aCI6Ii82MzIyNDY1Ni8zMjE4MzI3NzUtZTIxNGUxOTktOTFhNC00Yzc5LTkxNGEtMmNiYzk1YzFlZDAzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA4MTcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYjkyZjMzMTM5NWQ3ODhiMmRmNThiM2FhZTY5ODliMTc4MWNmMzkyYWI0MWUzNDc0OTQ0NGM5MGNhNmJkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A71HDggdeg47w7SZCa5sgAbccWKHqGYGiQslfZbaTxI)

是想获取store中的language值吗，试试这样
<img width="1236" alt="image" src="https://github.com/youlaitech/vue3-element-admin/assets/24354441/41a8ddc1-872b-4bc3-9737-ada76bd5fdf0">
