### ISSUE TITLE
Routing works , however url refresh , leads to 404, after deployment 

### ISSUE THREAD

**Issue by ShamineDsouza** [youlaitech/vue3-element-admin#76]
This solution works perfectly in local environment . The issue starts after deployment , the login is using keycloak and it redirects perfectly . However , if the above url is refreshed manually , it crashes sending 404. 

It works perfectly for routing in deployed version, however fails when and gives 404 , when same url refreshed.

I am logging in using keycloak login as soon as the web url is clicked 

PLease help.

**Comment by AnAloneJaver** [comment]
Our project did not use keylock, it seems that your problem lies in the interaction between keylock and the project. You should check if there is a 404 issue with the route after refreshing.
